{% set version = "0.2.0" %}
{% set sha256 = "ec3669bddd85693e142c5245f2dca60c663529dc15f20f2d1a7caf84b0e46edf" %}


package:
  name: pcaone
  version: '{{ version }}'

source:
  url: https://github.com/Zilong-Li/PCAone/archive/refs/tags/v{{ version }}.tar.gz # [x86_64]
  sha256: '{{ sha256 }}'

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - sysroot_linux-64 2.17 # [linux]
    - intel-openmp

  host:
    - mkl
    - mkl-include
    - intel-openmp
    - zlib

  run:
    - mkl
    - intel-openmp
    - zlib

test:
  commands:
    - PCAone --help

about:
  home: https://github.com/Zilong-Li/PCAone
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: PCAone - Principal Component Analysis All in One
  doc_url: https://github.com/Zilong-Li/PCAone
  dev_url: https://github.com/Zilong-Li/PCAone

extra:
  recipe-maintainers:
    - Zilong
